language: node_js
sudo: required
dist: trusty

node_js:
  - 'stable'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable

cache:
  directories:
    - node_modules
    - typings

before_install:
  - sudo apt-get update
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
